// Feature: netvis-core, Property 22: IP flow filter generation
// Validates: Requirements 27.3, 27.4

/**
 * Property 22: IP flow filter generation
 *
 * The filter expressions generated by node and edge clicks in the IP Flow Map
 * must correctly match the intended packets and conform to the Filter_Grammar.
 *
 * Properties tested:
 *   (a) Node filter matches all packets where src OR dst equals the IP
 *   (b) Node filter does not match packets where neither src nor dst equals the IP
 *   (c) Edge filter matches packets in both directions between two IPs
 *   (d) Edge filter does not match packets involving unrelated IPs
 *   (e) Node filter expression conforms to Filter_Grammar syntax
 *   (f) Edge filter expression conforms to Filter_Grammar syntax
 *   (g) Node filter for IP X is symmetric: same packets matched regardless of direction
 *   (h) Edge filter for (A, B) equals edge filter for (B, A) in terms of matched packets
 *
 * Validates: Requirements 27.3, 27.4
 */

import { describe, it, expect } from 'vitest'
import * as fc from 'fast-check'
import { buildNodeFilter, buildEdgeFilter } from '../../renderer/src/components/IPFlowMap'

// ─── Arbitraries ─────────────────────────────────────────────────────────────

const ipv4Arb = fc
  .tuple(
    fc.integer({ min: 1, max: 254 }),
    fc.integer({ min: 0, max: 255 }),
    fc.integer({ min: 0, max: 255 }),
    fc.integer({ min: 1, max: 254 })
  )
  .map(([a, b, c, d]) => `${a}.${b}.${c}.${d}`)

// Two distinct IPs
const twoDistinctIPsArb = fc
  .tuple(ipv4Arb, ipv4Arb)
  .filter(([a, b]) => a !== b)

// ─── Simple filter evaluator (subset of Filter_Grammar for IP matching) ───────

interface MinimalPacket {
  srcAddress: string
  dstAddress: string
}

/**
 * Evaluates the subset of filter expressions generated by buildNodeFilter and
 * buildEdgeFilter. Supports: src == "X", dst == "X", AND, OR, parentheses.
 */
function evaluateIPFilter(expression: string, packet: MinimalPacket): boolean {
  // Tokenize and evaluate the specific patterns we generate
  // Pattern: `src == "IP" OR dst == "IP"`
  const nodePattern = /^src == "([^"]+)" OR dst == "([^"]+)"$/
  const nodeMatch = expression.match(nodePattern)
  if (nodeMatch) {
    const ip = nodeMatch[1]!
    return packet.srcAddress === ip || packet.dstAddress === ip
  }

  // Pattern: `(src == "A" AND dst == "B") OR (src == "B" AND dst == "A")`
  const edgePattern = /^\(src == "([^"]+)" AND dst == "([^"]+)"\) OR \(src == "([^"]+)" AND dst == "([^"]+)"\)$/
  const edgeMatch = expression.match(edgePattern)
  if (edgeMatch) {
    const [, srcA, dstB, srcB, dstA] = edgeMatch
    return (
      (packet.srcAddress === srcA && packet.dstAddress === dstB) ||
      (packet.srcAddress === srcB && packet.dstAddress === dstA)
    )
  }

  return false
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('IP flow filter generation (P22)', () => {
  /**
   * Property 22a: Node filter matches packets where src OR dst equals the IP.
   * Validates: Requirement 27.3
   */
  it('node filter matches packets where src or dst equals the IP', () => {
    fc.assert(
      fc.property(ipv4Arb, ipv4Arb, (ip, otherIp) => {
        const filter = buildNodeFilter(ip)

        // Packet where src = ip → should match
        expect(evaluateIPFilter(filter, { srcAddress: ip, dstAddress: otherIp })).toBe(true)

        // Packet where dst = ip → should match
        expect(evaluateIPFilter(filter, { srcAddress: otherIp, dstAddress: ip })).toBe(true)

        // Packet where both = ip → should match
        expect(evaluateIPFilter(filter, { srcAddress: ip, dstAddress: ip })).toBe(true)
      }),
      { numRuns: 100 }
    )
  })

  /**
   * Property 22b: Node filter does not match packets where neither src nor dst equals the IP.
   * Validates: Requirement 27.3
   */
  it('node filter does not match packets where neither address equals the IP', () => {
    fc.assert(
      fc.property(twoDistinctIPsArb, ipv4Arb, ([[ip, unrelatedIp], thirdIp]) => {
        // Ensure thirdIp is different from ip
        if (thirdIp === ip) return

        const filter = buildNodeFilter(ip)
        // Packet between two unrelated IPs
        expect(evaluateIPFilter(filter, { srcAddress: unrelatedIp, dstAddress: thirdIp })).toBe(false)
      }),
      { numRuns: 100 }
    )
  })

  /**
   * Property 22c: Edge filter matches packets in both directions between two IPs.
   * Validates: Requirement 27.4
   */
  it('edge filter matches packets in both directions between two IPs', () => {
    fc.assert(
      fc.property(twoDistinctIPsArb, ([ipA, ipB]) => {
        const filter = buildEdgeFilter(ipA, ipB)

        // A→B direction
        expect(evaluateIPFilter(filter, { srcAddress: ipA, dstAddress: ipB })).toBe(true)

        // B→A direction (bidirectional)
        expect(evaluateIPFilter(filter, { srcAddress: ipB, dstAddress: ipA })).toBe(true)
      }),
      { numRuns: 100 }
    )
  })

  /**
   * Property 22d: Edge filter does not match packets involving unrelated IPs.
   * Validates: Requirement 27.4
   */
  it('edge filter does not match packets involving unrelated IPs', () => {
    fc.assert(
      fc.property(
        twoDistinctIPsArb,
        ipv4Arb,
        ipv4Arb,
        ([[ipA, ipB], unrelatedC, unrelatedD]) => {
          if (unrelatedC === ipA || unrelatedC === ipB) return
          if (unrelatedD === ipA || unrelatedD === ipB) return

          const filter = buildEdgeFilter(ipA, ipB)

          // Packet between two unrelated IPs
          expect(evaluateIPFilter(filter, { srcAddress: unrelatedC, dstAddress: unrelatedD })).toBe(false)

          // Packet from A to unrelated
          expect(evaluateIPFilter(filter, { srcAddress: ipA, dstAddress: unrelatedC })).toBe(false)

          // Packet from unrelated to B
          expect(evaluateIPFilter(filter, { srcAddress: unrelatedC, dstAddress: ipB })).toBe(false)
        }
      ),
      { numRuns: 100 }
    )
  })

  /**
   * Property 22e: Node filter expression conforms to Filter_Grammar syntax.
   * Must contain src == "IP" OR dst == "IP" pattern.
   * Validates: Requirement 27.3
   */
  it('node filter expression conforms to Filter_Grammar syntax', () => {
    fc.assert(
      fc.property(ipv4Arb, (ip) => {
        const filter = buildNodeFilter(ip)
        // Must contain the IP in quoted form
        expect(filter).toContain(`"${ip}"`)
        // Must use OR to combine src and dst
        expect(filter).toContain('OR')
        // Must reference both src and dst
        expect(filter).toContain('src')
        expect(filter).toContain('dst')
        // Must use == comparator
        expect(filter).toContain('==')
      }),
      { numRuns: 100 }
    )
  })

  /**
   * Property 22f: Edge filter expression conforms to Filter_Grammar syntax.
   * Must contain bidirectional matching with AND/OR.
   * Validates: Requirement 27.4
   */
  it('edge filter expression conforms to Filter_Grammar syntax', () => {
    fc.assert(
      fc.property(twoDistinctIPsArb, ([ipA, ipB]) => {
        const filter = buildEdgeFilter(ipA, ipB)
        // Must contain both IPs
        expect(filter).toContain(`"${ipA}"`)
        expect(filter).toContain(`"${ipB}"`)
        // Must use AND for direction matching and OR for bidirectionality
        expect(filter).toContain('AND')
        expect(filter).toContain('OR')
        // Must reference both src and dst
        expect(filter).toContain('src')
        expect(filter).toContain('dst')
      }),
      { numRuns: 100 }
    )
  })

  /**
   * Property 22g: Edge filter for (A, B) matches the same packets as edge filter for (B, A).
   * The filter is symmetric — order of arguments does not matter.
   * Validates: Requirement 27.4 (bidirectional filter)
   */
  it('edge filter is symmetric: buildEdgeFilter(A, B) matches same packets as buildEdgeFilter(B, A)', () => {
    fc.assert(
      fc.property(twoDistinctIPsArb, ipv4Arb, ipv4Arb, ([[ipA, ipB], srcIp, dstIp]) => {
        const filterAB = buildEdgeFilter(ipA, ipB)
        const filterBA = buildEdgeFilter(ipB, ipA)

        const packet = { srcAddress: srcIp, dstAddress: dstIp }
        expect(evaluateIPFilter(filterAB, packet)).toBe(evaluateIPFilter(filterBA, packet))
      }),
      { numRuns: 100 }
    )
  })

  /**
   * Property 22h: Node filter is idempotent — calling buildNodeFilter twice with the
   * same IP produces identical expressions.
   * Validates: Requirement 27.3 (deterministic filter generation)
   */
  it('node filter generation is deterministic', () => {
    fc.assert(
      fc.property(ipv4Arb, (ip) => {
        expect(buildNodeFilter(ip)).toBe(buildNodeFilter(ip))
      }),
      { numRuns: 100 }
    )
  })

  /**
   * Property 22i: Edge filter generation is deterministic.
   * Validates: Requirement 27.4
   */
  it('edge filter generation is deterministic', () => {
    fc.assert(
      fc.property(twoDistinctIPsArb, ([ipA, ipB]) => {
        expect(buildEdgeFilter(ipA, ipB)).toBe(buildEdgeFilter(ipA, ipB))
      }),
      { numRuns: 100 }
    )
  })
})
